CREATE TABLE Users (
    user_id int NOT NULL PRIMARY KEY DEFAULT 0,
    action text DEFAULT '',
    language text DEFAULT '',
    level int DEFAULT '',
    name text DEFAULT '',
    last_name text DEFAULT '',
    username text DEFAULT '',
    actionwithmes text DEFAULT '',
    game_id_reg_to_game int DEFAULT 0,
    sport_reg_to_game text DEFAULT '',
    date_reg_to_game int DEFAULT 0,
    time_reg_to_game int DEFAULT 0,
    seats_reg_to_game int DEFAULT 0,
    payment_reg_to_game text DEFAULT '',
    payment_status_reg_to_game text DEFAULT '',
    media_time_interval int DEFAULT 0,
    media_direction text DEFAULT '',
    media_limit int DEFAULT 0,
    media_launch_point int DEFAULT 0,
    del_game_game_id int DEFAULT 0,
    counter_mediagroup int DEFAULT 0,
    id_mediagroup text DEFAULT '',
    user_records_action  text DEFAULT '',
    user_records_sport text DEFAULT '',
    user_records_date int DEFAULT 0,
    user_records_time int DEFAULT 0,
    user_records_what_change text DEFAULT '',
    user_records_newseats int DEFAULT 0,
    user_records_changpayeorwhat text DEFAULT '',
    user_records_deleteorwhat text DEFAULT '',
    notifgameid int DEFAULT 0,
    last_time_use text DEFAULT '',
    exmess int DEFAULT 0,
    custom_language bool DEFAULT false,
    from_where text DEFAULT '',
    launch_point_reg_to_game int DEFAULT 0,
    us_set_lanuch_point int DEFAULT 0,
    us_set_what_set text DEFAULT '',
    us_set_game_id int DEFAULT 0,
    us_set_act_game text DEFAULT '',
    us_set_what_we_will_change text DEFAULT '',
    us_set_new_pay text DEFAULT ''
);

CREATE TABLE Schedule (
    game_id serial NOT NULL PRIMARY KEY DEFAULT 0,
    sport text DEFAULT '',
    date int DEFAULT 0,
    time DEFAULT 0,
    status int DEFAULT 0
);

CREATE TABLE MediaRepository (
    game_id int NOT NULL PRIMARY KEY DEFAULT 0,
    file_id text DEFAULT '',
    typeoffile text DEFAULT '',
    counter int DEFAULT 0,
    status int DEFAULT 0,
)